# Generated by Django 4.2.3 on 2023-07-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='image',
        ),
    ]
