# Generated by Django 4.2.3 on 2023-07-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_response_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='image',
            field=models.FileField(default=1, upload_to='images/response_user'),
            preserve_default=False,
        ),
    ]
