# Generated by Django 4.2.3 on 2026-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_response_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='response',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час'),
        ),
    ]
