# Generated by Django 4.2.3 on 2023-07-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_articles_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name="Ім'я")),
                ('about', models.TextField(max_length=256, verbose_name='Тема')),
                ('message', models.TextField(max_length=1024, verbose_name='Повідомлення')),
            ],
        ),
    ]
