# Generated by Django 4.2.3 on 2026-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_modern_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesite',
            name='title',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
    ]
